const data = [
  { name: "fa-500px", icon: "500px" },
  { name: "fa-adjust", icon: "Adjust" },
  { name: "fa-adn", icon: "Adn" },
  { name: "fa-align-center", icon: "Align center" },
  { name: "fa-align-justify", icon: "Align justify" },
  { name: "fa-align-left", icon: "Align left" },
  { name: "fa-align-right", icon: "Align right" },
  { name: "fa-amazon", icon: "Amazon" },
  { name: "fa-ambulance", icon: "Ambulance" },
  { name: "fa-anchor", icon: "Anchor" },
  { name: "fa-android", icon: "Android" },
  { name: "fa-angellist", icon: "Angellist" },
  { name: "fa-angle-double-down", icon: "Angle double down" },
  { name: "fa-angle-double-left", icon: "Angle double left" },
  { name: "fa-angle-double-right", icon: "Angle double right" },
  { name: "fa-angle-double-up", icon: "Angle double up" },
  { name: "fa-angle-down", icon: "Angle down" },
  { name: "fa-angle-left", icon: "Angle left" },
  { name: "fa-angle-right", icon: "Angle right" },
  { name: "fa-angle-up", icon: "Angle up" },
  { name: "fa-apple", icon: "Apple" },
  { name: "fa-archive", icon: "Archive" },
  { name: "fa-area-chart", icon: "Area chart" },
  { name: "fa-arrow-circle-down", icon: "Arrow circle down" },
  { name: "fa-arrow-circle-left", icon: "Arrow circle left" },
  { name: "fa-arrow-circle-o-down", icon: "Arrow circle o down" },
  { name: "fa-arrow-circle-o-left", icon: "Arrow circle o left" },
  { name: "fa-arrow-circle-o-right", icon: "Arrow circle o right" },
  { name: "fa-arrow-circle-o-up", icon: "Arrow circle o up" },
  { name: "fa-arrow-circle-right", icon: "Arrow circle right" },
  { name: "fa-arrow-circle-up", icon: "Arrow circle up" },
  { name: "fa-arrow-down", icon: "Arrow down" },
  { name: "fa-arrow-left", icon: "Arrow left" },
  { name: "fa-arrow-right", icon: "Arrow right" },
  { name: "fa-arrow-up", icon: "Arrow up" },
  { name: "fa-arrows", icon: "Arrows" },
  { name: "fa-arrows-alt", icon: "Arrows alt" },
  { name: "fa-arrows-h", icon: "Arrows h" },
  { name: "fa-arrows-v", icon: "Arrows v" },
  { name: "fa-asterisk", icon: "Asterisk" },
  { name: "fa-at", icon: "At" },
  { name: "fa-backward", icon: "Backward" },
  { name: "fa-balance-scale", icon: "Balance scale" },
  { name: "fa-ban", icon: "Ban" },
  { name: "fa-bar-chart", icon: "Bar chart" },
  { name: "fa-barcode", icon: "Barcode" },
  { name: "fa-bars", icon: "Bars" },
  { name: "fa-battery-empty", icon: "Battery empty" },
  { name: "fa-battery-full", icon: "Battery full" },
  { name: "fa-battery-half", icon: "Battery half" },
  { name: "fa-battery-quarter", icon: "Battery quarter" },
  { name: "fa-battery-three-quarters", icon: "Battery three quarters" },
  { name: "fa-bed", icon: "Bed" },
  { name: "fa-beer", icon: "Beer" },
  { name: "fa-behance", icon: "Behance" },
  { name: "fa-behance-square", icon: "Behance square" },
  { name: "fa-bell", icon: "Bell" },
  { name: "fa-bell-o", icon: "Bell o" },
  { name: "fa-bell-slash", icon: "Bell slash" },
  { name: "fa-bell-slash-o", icon: "Bell slash o" },
  { name: "fa-bicycle", icon: "Bicycle" },
  { name: "fa-binoculars", icon: "Binoculars" },
  { name: "fa-birthday-cake", icon: "Birthday cake" },
  { name: "fa-bitbucket", icon: "Bitbucket" },
  { name: "fa-bitbucket-square", icon: "Bitbucket square" },
  { name: "fa-black-tie", icon: "Black tie" },
  { name: "fa-bold", icon: "Bold" },
  { name: "fa-bolt", icon: "Bolt" },
  { name: "fa-bomb", icon: "Bomb" },
  { name: "fa-book", icon: "Book" },
  { name: "fa-bookmark", icon: "Bookmark" },
  { name: "fa-bookmark-o", icon: "Bookmark o" },
  { name: "fa-briefcase", icon: "Briefcase" },
  { name: "fa-btc", icon: "Btc" },
  { name: "fa-bug", icon: "Bug" },
  { name: "fa-building", icon: "Building" },
  { name: "fa-building-o", icon: "Building o" },
  { name: "fa-bullhorn", icon: "Bullhorn" },
  { name: "fa-bullseye", icon: "Bullseye" },
  { name: "fa-bus", icon: "Bus" },
  { name: "fa-buysellads", icon: "Buysellads" },
  { name: "fa-calculator", icon: "Calculator" },
  { name: "fa-calendar", icon: "Calendar" },
  { name: "fa-calendar-check-o", icon: "Calendar check o" },
  { name: "fa-calendar-minus-o", icon: "Calendar minus o" },
  { name: "fa-calendar-o", icon: "Calendar o" },
  { name: "fa-calendar-plus-o", icon: "Calendar plus o" },
  { name: "fa-calendar-times-o", icon: "Calendar times o" },
  { name: "fa-camera", icon: "Camera" },
  { name: "fa-camera-retro", icon: "Camera retro" },
  { name: "fa-car", icon: "Car" },
  { name: "fa-caret-down", icon: "Caret down" },
  { name: "fa-caret-left", icon: "Caret left" },
  { name: "fa-caret-right", icon: "Caret right" },
  { name: "fa-caret-square-o-down", icon: "Caret square o down" },
  { name: "fa-caret-square-o-left", icon: "Caret square o left" },
  { name: "fa-caret-square-o-right", icon: "Caret square o right" },
  { name: "fa-caret-square-o-up", icon: "Caret square o up" },
  { name: "fa-caret-up", icon: "Caret up" },
  { name: "fa-cart-arrow-down", icon: "Cart arrow down" },
  { name: "fa-cart-plus", icon: "Cart plus" },
  { name: "fa-cc", icon: "Cc" },
  { name: "fa-cc-amex", icon: "Cc amex" },
  { name: "fa-cc-diners-club", icon: "Cc diners club" },
  { name: "fa-cc-discover", icon: "Cc discover" },
  { name: "fa-cc-jcb", icon: "Cc jcb" },
  { name: "fa-cc-mastercard", icon: "Cc mastercard" },
  { name: "fa-cc-paypal", icon: "Cc paypal" },
  { name: "fa-cc-stripe", icon: "Cc stripe" },
  { name: "fa-cc-visa", icon: "Cc visa" },
  { name: "fa-certificate", icon: "Certificate" },
  { name: "fa-chain-broken", icon: "Chain broken" },
  { name: "fa-check", icon: "Check" },
  { name: "fa-check-circle", icon: "Check circle" },
  { name: "fa-check-circle-o", icon: "Check circle o" },
  { name: "fa-check-square", icon: "Check square" },
  { name: "fa-check-square-o", icon: "Check square o" },
  { name: "fa-chevron-circle-down", icon: "Chevron circle down" },
  { name: "fa-chevron-circle-left", icon: "Chevron circle left" },
  { name: "fa-chevron-circle-right", icon: "Chevron circle right" },
  { name: "fa-chevron-circle-up", icon: "Chevron circle up" },
  { name: "fa-chevron-down", icon: "Chevron down" },
  { name: "fa-chevron-left", icon: "Chevron left" },
  { name: "fa-chevron-right", icon: "Chevron right" },
  { name: "fa-chevron-up", icon: "Chevron up" },
  { name: "fa-child", icon: "Child" },
  { name: "fa-chrome", icon: "Chrome" },
  { name: "fa-circle", icon: "Circle" },
  { name: "fa-circle-o", icon: "Circle o" },
  { name: "fa-circle-o-notch", icon: "Circle o notch" },
  { name: "fa-circle-thin", icon: "Circle thin" },
  { name: "fa-clipboard", icon: "Clipboard" },
  { name: "fa-clock-o", icon: "Clock o" },
  { name: "fa-clone", icon: "Clone" },
  { name: "fa-cloud", icon: "Cloud" },
  { name: "fa-cloud-download", icon: "Cloud download" },
  { name: "fa-cloud-upload", icon: "Cloud upload" },
  { name: "fa-code", icon: "Code" },
  { name: "fa-code-fork", icon: "Code fork" },
  { name: "fa-codepen", icon: "Codepen" },
  { name: "fa-coffee", icon: "Coffee" },
  { name: "fa-cog", icon: "Cog" },
  { name: "fa-cogs", icon: "Cogs" },
  { name: "fa-columns", icon: "Columns" },
  { name: "fa-comment", icon: "Comment" },
  { name: "fa-comment-o", icon: "Comment o" },
  { name: "fa-commenting", icon: "Commenting" },
  { name: "fa-commenting-o", icon: "Commenting o" },
  { name: "fa-comments", icon: "Comments" },
  { name: "fa-comments-o", icon: "Comments o" },
  { name: "fa-compass", icon: "Compass" },
  { name: "fa-compress", icon: "Compress" },
  { name: "fa-connectdevelop", icon: "Connectdevelop" },
  { name: "fa-contao", icon: "Contao" },
  { name: "fa-copyright", icon: "Copyright" },
  { name: "fa-creative-commons", icon: "Creative commons" },
  { name: "fa-credit-card", icon: "Credit card" },
  { name: "fa-crop", icon: "Crop" },
  { name: "fa-crosshairs", icon: "Crosshairs" },
  { name: "fa-css3", icon: "Css3" },
  { name: "fa-cube", icon: "Cube" },
  { name: "fa-cubes", icon: "Cubes" },
  { name: "fa-cutlery", icon: "Cutlery" },
  { name: "fa-dashcube", icon: "Dashcube" },
  { name: "fa-database", icon: "Database" },
  { name: "fa-delicious", icon: "Delicious" },
  { name: "fa-desktop", icon: "Desktop" },
  { name: "fa-deviantart", icon: "Deviantart" },
  { name: "fa-diamond", icon: "Diamond" },
  { name: "fa-digg", icon: "Digg" },
  { name: "fa-dot-circle-o", icon: "Dot circle o" },
  { name: "fa-download", icon: "Download" },
  { name: "fa-dribbble", icon: "Dribbble" },
  { name: "fa-dropbox", icon: "Dropbox" },
  { name: "fa-drupal", icon: "Drupal" },
  { name: "fa-eject", icon: "Eject" },
  { name: "fa-ellipsis-h", icon: "Ellipsis h" },
  { name: "fa-ellipsis-v", icon: "Ellipsis v" },
  { name: "fa-empire", icon: "Empire" },
  { name: "fa-envelope", icon: "Envelope" },
  { name: "fa-envelope-o", icon: "Envelope o" },
  { name: "fa-envelope-square", icon: "Envelope square" },
  { name: "fa-eraser", icon: "Eraser" },
  { name: "fa-eur", icon: "Eur" },
  { name: "fa-exchange", icon: "Exchange" },
  { name: "fa-exclamation", icon: "Exclamation" },
  { name: "fa-exclamation-circle", icon: "Exclamation circle" },
  { name: "fa-exclamation-triangle", icon: "Exclamation triangle" },
  { name: "fa-expand", icon: "Expand" },
  { name: "fa-expeditedssl", icon: "Expeditedssl" },
  { name: "fa-external-link", icon: "External link" },
  { name: "fa-external-link-square", icon: "External link square" },
  { name: "fa-eye", icon: "Eye" },
  { name: "fa-eye-slash", icon: "Eye slash" },
  { name: "fa-eyedropper", icon: "Eyedropper" },
  { name: "fa-facebook", icon: "Facebook" },
  { name: "fa-facebook-official", icon: "Facebook official" },
  { name: "fa-facebook-square", icon: "Facebook square" },
  { name: "fa-fast-backward", icon: "Fast backward" },
  { name: "fa-fast-forward", icon: "Fast forward" },
  { name: "fa-fax", icon: "Fax" },
  { name: "fa-female", icon: "Female" },
  { name: "fa-fighter-jet", icon: "Fighter jet" },
  { name: "fa-file", icon: "File" },
  { name: "fa-file-archive-o", icon: "File archive o" },
  { name: "fa-file-audio-o", icon: "File audio o" },
  { name: "fa-file-code-o", icon: "File code o" },
  { name: "fa-file-excel-o", icon: "File excel o" },
  { name: "fa-file-image-o", icon: "File image o" },
  { name: "fa-file-o", icon: "File o" },
  { name: "fa-file-pdf-o", icon: "File pdf o" },
  { name: "fa-file-powerpoint-o", icon: "File powerpoint o" },
  { name: "fa-file-text", icon: "File text" },
  { name: "fa-file-text-o", icon: "File text o" },
  { name: "fa-file-video-o", icon: "File video o" },
  { name: "fa-file-word-o", icon: "File word o" },
  { name: "fa-files-o", icon: "Files o" },
  { name: "fa-film", icon: "Film" },
  { name: "fa-filter", icon: "Filter" },
  { name: "fa-fire", icon: "Fire" },
  { name: "fa-fire-extinguisher", icon: "Fire extinguisher" },
  { name: "fa-firefox", icon: "Firefox" },
  { name: "fa-flag", icon: "Flag" },
  { name: "fa-flag-checkered", icon: "Flag checkered" },
  { name: "fa-flag-o", icon: "Flag o" },
  { name: "fa-flask", icon: "Flask" },
  { name: "fa-flickr", icon: "Flickr" },
  { name: "fa-floppy-o", icon: "Floppy o" },
  { name: "fa-folder", icon: "Folder" },
  { name: "fa-folder-o", icon: "Folder o" },
  { name: "fa-folder-open", icon: "Folder open" },
  { name: "fa-folder-open-o", icon: "Folder open o" },
  { name: "fa-font", icon: "Font" },
  { name: "fa-fonticons", icon: "Fonticons" },
  { name: "fa-forumbee", icon: "Forumbee" },
  { name: "fa-forward", icon: "Forward" },
  { name: "fa-foursquare", icon: "Foursquare" },
  { name: "fa-frown-o", icon: "Frown o" },
  { name: "fa-futbol-o", icon: "Futbol o" },
  { name: "fa-gamepad", icon: "Gamepad" },
  { name: "fa-gavel", icon: "Gavel" },
  { name: "fa-gbp", icon: "Gbp" },
  { name: "fa-genderless", icon: "Genderless" },
  { name: "fa-get-pocket", icon: "Get pocket" },
  { name: "fa-gg", icon: "Gg" },
  { name: "fa-gg-circle", icon: "Gg circle" },
  { name: "fa-gift", icon: "Gift" },
  { name: "fa-git", icon: "Git" },
  { name: "fa-git-square", icon: "Git square" },
  { name: "fa-github", icon: "Github" },
  { name: "fa-github-alt", icon: "Github alt" },
  { name: "fa-github-square", icon: "Github square" },
  { name: "fa-glass", icon: "Glass" },
  { name: "fa-globe", icon: "Globe" },
  { name: "fa-google", icon: "Google" },
  { name: "fa-google-plus", icon: "Google plus" },
  { name: "fa-google-plus-square", icon: "Google plus square" },
  { name: "fa-google-wallet", icon: "Google wallet" },
  { name: "fa-graduation-cap", icon: "Graduation cap" },
  { name: "fa-gratipay", icon: "Gratipay" },
  { name: "fa-h-square", icon: "H square" },
  { name: "fa-hacker-news", icon: "Hacker news" },
  { name: "fa-hand-lizard-o", icon: "Hand lizard o" },
  { name: "fa-hand-o-down", icon: "Hand o down" },
  { name: "fa-hand-o-left", icon: "Hand o left" },
  { name: "fa-hand-o-right", icon: "Hand o right" },
  { name: "fa-hand-o-up", icon: "Hand o up" },
  { name: "fa-hand-paper-o", icon: "Hand paper o" },
  { name: "fa-hand-peace-o", icon: "Hand peace o" },
  { name: "fa-hand-pointer-o", icon: "Hand pointer o" },
  { name: "fa-hand-rock-o", icon: "Hand rock o" },
  { name: "fa-hand-scissors-o", icon: "Hand scissors o" },
  { name: "fa-hand-spock-o", icon: "Hand spock o" },
  { name: "fa-hdd-o", icon: "Hdd o" },
  { name: "fa-header", icon: "Header" },
  { name: "fa-headphones", icon: "Headphones" },
  { name: "fa-heart", icon: "Heart" },
  { name: "fa-heart-o", icon: "Heart o" },
  { name: "fa-heartbeat", icon: "Heartbeat" },
  { name: "fa-history", icon: "History" },
  { name: "fa-home", icon: "Home" },
  { name: "fa-hospital-o", icon: "Hospital o" },
  { name: "fa-hourglass", icon: "Hourglass" },
  { name: "fa-hourglass-end", icon: "Hourglass end" },
  { name: "fa-hourglass-half", icon: "Hourglass half" },
  { name: "fa-hourglass-o", icon: "Hourglass o" },
  { name: "fa-hourglass-start", icon: "Hourglass start" },
  { name: "fa-houzz", icon: "Houzz" },
  { name: "fa-html5", icon: "Html5" },
  { name: "fa-i-cursor", icon: "I cursor" },
  { name: "fa-ils", icon: "Ils" },
  { name: "fa-inbox", icon: "Inbox" },
  { name: "fa-indent", icon: "Indent" },
  { name: "fa-industry", icon: "Industry" },
  { name: "fa-info", icon: "Info" },
  { name: "fa-info-circle", icon: "Info circle" },
  { name: "fa-inr", icon: "Inr" },
  { name: "fa-instagram", icon: "Instagram" },
  { name: "fa-internet-explorer", icon: "Internet explorer" },
  { name: "fa-ioxhost", icon: "Ioxhost" },
  { name: "fa-italic", icon: "Italic" },
  { name: "fa-joomla", icon: "Joomla" },
  { name: "fa-jpy", icon: "Jpy" },
  { name: "fa-jsfiddle", icon: "Jsfiddle" },
  { name: "fa-key", icon: "Key" },
  { name: "fa-keyboard-o", icon: "Keyboard o" },
  { name: "fa-krw", icon: "Krw" },
  { name: "fa-language", icon: "Language" },
  { name: "fa-laptop", icon: "Laptop" },
  { name: "fa-lastfm", icon: "Lastfm" },
  { name: "fa-lastfm-square", icon: "Lastfm square" },
  { name: "fa-leaf", icon: "Leaf" },
  { name: "fa-leanpub", icon: "Leanpub" },
  { name: "fa-lemon-o", icon: "Lemon o" },
  { name: "fa-level-down", icon: "Level down" },
  { name: "fa-level-up", icon: "Level up" },
  { name: "fa-life-ring", icon: "Life ring" },
  { name: "fa-lightbulb-o", icon: "Lightbulb o" },
  { name: "fa-line-chart", icon: "Line chart" },
  { name: "fa-link", icon: "Link" },
  { name: "fa-linkedin", icon: "Linkedin" },
  { name: "fa-linkedin-square", icon: "Linkedin square" },
  { name: "fa-linux", icon: "Linux" },
  { name: "fa-list", icon: "List" },
  { name: "fa-list-alt", icon: "List alt" },
  { name: "fa-list-ol", icon: "List ol" },
  { name: "fa-list-ul", icon: "List ul" },
  { name: "fa-location-arrow", icon: "Location arrow" },
  { name: "fa-lock", icon: "Lock" },
  { name: "fa-long-arrow-down", icon: "Long arrow down" },
  { name: "fa-long-arrow-left", icon: "Long arrow left" },
  { name: "fa-long-arrow-right", icon: "Long arrow right" },
  { name: "fa-long-arrow-up", icon: "Long arrow up" },
  { name: "fa-magic", icon: "Magic" },
  { name: "fa-magnet", icon: "Magnet" },
  { name: "fa-male", icon: "Male" },
  { name: "fa-map", icon: "Map" },
  { name: "fa-map-marker", icon: "Map marker" },
  { name: "fa-map-o", icon: "Map o" },
  { name: "fa-map-pin", icon: "Map pin" },
  { name: "fa-map-signs", icon: "Map signs" },
  { name: "fa-mars", icon: "Mars" },
  { name: "fa-mars-double", icon: "Mars double" },
  { name: "fa-mars-stroke", icon: "Mars stroke" },
  { name: "fa-mars-stroke-h", icon: "Mars stroke h" },
  { name: "fa-mars-stroke-v", icon: "Mars stroke v" },
  { name: "fa-maxcdn", icon: "Maxcdn" },
  { name: "fa-meanpath", icon: "Meanpath" },
  { name: "fa-medium", icon: "Medium" },
  { name: "fa-medkit", icon: "Medkit" },
  { name: "fa-meh-o", icon: "Meh o" },
  { name: "fa-mercury", icon: "Mercury" },
  { name: "fa-microphone", icon: "Microphone" },
  { name: "fa-microphone-slash", icon: "Microphone slash" },
  { name: "fa-minus", icon: "Minus" },
  { name: "fa-minus-circle", icon: "Minus circle" },
  { name: "fa-minus-square", icon: "Minus square" },
  { name: "fa-minus-square-o", icon: "Minus square o" },
  { name: "fa-mobile", icon: "Mobile" },
  { name: "fa-money", icon: "Money" },
  { name: "fa-moon-o", icon: "Moon o" },
  { name: "fa-motorcycle", icon: "Motorcycle" },
  { name: "fa-mouse-pointer", icon: "Mouse pointer" },
  { name: "fa-music", icon: "Music" },
  { name: "fa-neuter", icon: "Neuter" },
  { name: "fa-newspaper-o", icon: "Newspaper o" },
  { name: "fa-object-group", icon: "Object group" },
  { name: "fa-object-ungroup", icon: "Object ungroup" },
  { name: "fa-odnoklassniki", icon: "Odnoklassniki" },
  { name: "fa-odnoklassniki-square", icon: "Odnoklassniki square" },
  { name: "fa-opencart", icon: "Opencart" },
  { name: "fa-openid", icon: "Openid" },
  { name: "fa-opera", icon: "Opera" },
  { name: "fa-optin-monster", icon: "Optin monster" },
  { name: "fa-outdent", icon: "Outdent" },
  { name: "fa-pagelines", icon: "Pagelines" },
  { name: "fa-paint-brush", icon: "Paint brush" },
  { name: "fa-paper-plane", icon: "Paper plane" },
  { name: "fa-paper-plane-o", icon: "Paper plane o" },
  { name: "fa-paperclip", icon: "Paperclip" },
  { name: "fa-paragraph", icon: "Paragraph" },
  { name: "fa-pause", icon: "Pause" },
  { name: "fa-paw", icon: "Paw" },
  { name: "fa-paypal", icon: "Paypal" },
  { name: "fa-pencil", icon: "Pencil" },
  { name: "fa-pencil-square", icon: "Pencil square" },
  { name: "fa-pencil-square-o", icon: "Pencil square o" },
  { name: "fa-phone", icon: "Phone" },
  { name: "fa-phone-square", icon: "Phone square" },
  { name: "fa-picture-o", icon: "Picture o" },
  { name: "fa-pie-chart", icon: "Pie chart" },
  { name: "fa-pied-piper", icon: "Pied piper" },
  { name: "fa-pied-piper-alt", icon: "Pied piper alt" },
  { name: "fa-pinterest", icon: "Pinterest" },
  { name: "fa-pinterest-p", icon: "Pinterest p" },
  { name: "fa-pinterest-square", icon: "Pinterest square" },
  { name: "fa-plane", icon: "Plane" },
  { name: "fa-play", icon: "Play" },
  { name: "fa-play-circle", icon: "Play circle" },
  { name: "fa-play-circle-o", icon: "Play circle o" },
  { name: "fa-plug", icon: "Plug" },
  { name: "fa-plus", icon: "Plus" },
  { name: "fa-plus-circle", icon: "Plus circle" },
  { name: "fa-plus-square", icon: "Plus square" },
  { name: "fa-plus-square-o", icon: "Plus square o" },
  { name: "fa-power-off", icon: "Power off" },
  { name: "fa-print", icon: "Print" },
  { name: "fa-puzzle-piece", icon: "Puzzle piece" },
  { name: "fa-qq", icon: "Qq" },
  { name: "fa-qrcode", icon: "Qrcode" },
  { name: "fa-question", icon: "Question" },
  { name: "fa-question-circle", icon: "Question circle" },
  { name: "fa-quote-left", icon: "Quote left" },
  { name: "fa-quote-right", icon: "Quote right" },
  { name: "fa-random", icon: "Random" },
  { name: "fa-rebel", icon: "Rebel" },
  { name: "fa-recycle", icon: "Recycle" },
  { name: "fa-reddit", icon: "Reddit" },
  { name: "fa-reddit-square", icon: "Reddit square" },
  { name: "fa-refresh", icon: "Refresh" },
  { name: "fa-registered", icon: "Registered" },
  { name: "fa-renren", icon: "Renren" },
  { name: "fa-repeat", icon: "Repeat" },
  { name: "fa-reply", icon: "Reply" },
  { name: "fa-reply-all", icon: "Reply all" },
  { name: "fa-retweet", icon: "Retweet" },
  { name: "fa-road", icon: "Road" },
  { name: "fa-rocket", icon: "Rocket" },
  { name: "fa-rss", icon: "Rss" },
  { name: "fa-rss-square", icon: "Rss square" },
  { name: "fa-rub", icon: "Rub" },
  { name: "fa-safari", icon: "Safari" },
  { name: "fa-scissors", icon: "Scissors" },
  { name: "fa-search", icon: "Search" },
  { name: "fa-search-minus", icon: "Search minus" },
  { name: "fa-search-plus", icon: "Search plus" },
  { name: "fa-sellsy", icon: "Sellsy" },
  { name: "fa-server", icon: "Server" },
  { name: "fa-share", icon: "Share" },
  { name: "fa-share-alt", icon: "Share alt" },
  { name: "fa-share-alt-square", icon: "Share alt square" },
  { name: "fa-share-square", icon: "Share square" },
  { name: "fa-share-square-o", icon: "Share square o" },
  { name: "fa-shield", icon: "Shield" },
  { name: "fa-ship", icon: "Ship" },
  { name: "fa-shirtsinbulk", icon: "Shirtsinbulk" },
  { name: "fa-shopping-cart", icon: "Shopping cart" },
  { name: "fa-sign-in", icon: "Sign in" },
  { name: "fa-sign-out", icon: "Sign out" },
  { name: "fa-signal", icon: "Signal" },
  { name: "fa-simplybuilt", icon: "Simplybuilt" },
  { name: "fa-sitemap", icon: "Sitemap" },
  { name: "fa-skyatlas", icon: "Skyatlas" },
  { name: "fa-skype", icon: "Skype" },
  { name: "fa-slack", icon: "Slack" },
  { name: "fa-sliders", icon: "Sliders" },
  { name: "fa-slideshare", icon: "Slideshare" },
  { name: "fa-smile-o", icon: "Smile o" },
  { name: "fa-sort", icon: "Sort" },
  { name: "fa-sort-alpha-asc", icon: "Sort alpha asc" },
  { name: "fa-sort-alpha-desc", icon: "Sort alpha desc" },
  { name: "fa-sort-amount-asc", icon: "Sort amount asc" },
  { name: "fa-sort-amount-desc", icon: "Sort amount desc" },
  { name: "fa-sort-asc", icon: "Sort asc" },
  { name: "fa-sort-desc", icon: "Sort desc" },
  { name: "fa-sort-numeric-asc", icon: "Sort numeric asc" },
  { name: "fa-sort-numeric-desc", icon: "Sort numeric desc" },
  { name: "fa-soundcloud", icon: "Soundcloud" },
  { name: "fa-space-shuttle", icon: "Space shuttle" },
  { name: "fa-spinner", icon: "Spinner" },
  { name: "fa-spoon", icon: "Spoon" },
  { name: "fa-spotify", icon: "Spotify" },
  { name: "fa-square", icon: "Square" },
  { name: "fa-square-o", icon: "Square o" },
  { name: "fa-stack-exchange", icon: "Stack exchange" },
  { name: "fa-stack-overflow", icon: "Stack overflow" },
  { name: "fa-star", icon: "Star" },
  { name: "fa-star-half", icon: "Star half" },
  { name: "fa-star-half-o", icon: "Star half o" },
  { name: "fa-star-o", icon: "Star o" },
  { name: "fa-steam", icon: "Steam" },
  { name: "fa-steam-square", icon: "Steam square" },
  { name: "fa-step-backward", icon: "Step backward" },
  { name: "fa-step-forward", icon: "Step forward" },
  { name: "fa-stethoscope", icon: "Stethoscope" },
  { name: "fa-sticky-note", icon: "Sticky note" },
  { name: "fa-sticky-note-o", icon: "Sticky note o" },
  { name: "fa-stop", icon: "Stop" },
  { name: "fa-street-view", icon: "Street view" },
  { name: "fa-strikethrough", icon: "Strikethrough" },
  { name: "fa-stumbleupon", icon: "Stumbleupon" },
  { name: "fa-stumbleupon-circle", icon: "Stumbleupon circle" },
  { name: "fa-subscript", icon: "Subscript" },
  { name: "fa-subway", icon: "Subway" },
  { name: "fa-suitcase", icon: "Suitcase" },
  { name: "fa-sun-o", icon: "Sun o" },
  { name: "fa-superscript", icon: "Superscript" },
  { name: "fa-table", icon: "Table" },
  { name: "fa-tablet", icon: "Tablet" },
  { name: "fa-tachometer", icon: "Tachometer" },
  { name: "fa-tag", icon: "Tag" },
  { name: "fa-tags", icon: "Tags" },
  { name: "fa-tasks", icon: "Tasks" },
  { name: "fa-taxi", icon: "Taxi" },
  { name: "fa-television", icon: "Television" },
  { name: "fa-tencent-weibo", icon: "Tencent weibo" },
  { name: "fa-terminal", icon: "Terminal" },
  { name: "fa-text-height", icon: "Text height" },
  { name: "fa-text-width", icon: "Text width" },
  { name: "fa-th", icon: "Th" },
  { name: "fa-th-large", icon: "Th large" },
  { name: "fa-th-list", icon: "Th list" },
  { name: "fa-thumb-tack", icon: "Thumb tack" },
  { name: "fa-thumbs-down", icon: "Thumbs down" },
  { name: "fa-thumbs-o-down", icon: "Thumbs o down" },
  { name: "fa-thumbs-o-up", icon: "Thumbs o up" },
  { name: "fa-thumbs-up", icon: "Thumbs up" },
  { name: "fa-ticket", icon: "Ticket" },
  { name: "fa-times", icon: "Times" },
  { name: "fa-times-circle", icon: "Times circle" },
  { name: "fa-times-circle-o", icon: "Times circle o" },
  { name: "fa-tint", icon: "Tint" },
  { name: "fa-toggle-off", icon: "Toggle off" },
  { name: "fa-toggle-on", icon: "Toggle on" },
  { name: "fa-trademark", icon: "Trademark" },
  { name: "fa-train", icon: "Train" },
  { name: "fa-transgender", icon: "Transgender" },
  { name: "fa-transgender-alt", icon: "Transgender alt" },
  { name: "fa-trash", icon: "Trash" },
  { name: "fa-trash-o", icon: "Trash o" },
  { name: "fa-tree", icon: "Tree" },
  { name: "fa-trello", icon: "Trello" },
  { name: "fa-tripadvisor", icon: "Tripadvisor" },
  { name: "fa-trophy", icon: "Trophy" },
  { name: "fa-truck", icon: "Truck" },
  { name: "fa-try", icon: "Try" },
  { name: "fa-tty", icon: "Tty" },
  { name: "fa-tumblr", icon: "Tumblr" },
  { name: "fa-tumblr-square", icon: "Tumblr square" },
  { name: "fa-twitch", icon: "Twitch" },
  { name: "fa-twitter", icon: "Twitter" },
  { name: "fa-twitter-square", icon: "Twitter square" },
  { name: "fa-umbrella", icon: "Umbrella" },
  { name: "fa-underline", icon: "Underline" },
  { name: "fa-undo", icon: "Undo" },
  { name: "fa-university", icon: "University" },
  { name: "fa-unlock", icon: "Unlock" },
  { name: "fa-unlock-alt", icon: "Unlock alt" },
  { name: "fa-upload", icon: "Upload" },
  { name: "fa-usd", icon: "Usd" },
  { name: "fa-user", icon: "User" },
  { name: "fa-user-md", icon: "User md" },
  { name: "fa-user-plus", icon: "User plus" },
  { name: "fa-user-secret", icon: "User secret" },
  { name: "fa-user-times", icon: "User times" },
  { name: "fa-users", icon: "Users" },
  { name: "fa-venus", icon: "Venus" },
  { name: "fa-venus-double", icon: "Venus double" },
  { name: "fa-venus-mars", icon: "Venus mars" },
  { name: "fa-viacoin", icon: "Viacoin" },
  { name: "fa-video-camera", icon: "Video camera" },
  { name: "fa-vimeo", icon: "Vimeo" },
  { name: "fa-vimeo-square", icon: "Vimeo square" },
  { name: "fa-vine", icon: "Vine" },
  { name: "fa-vk", icon: "Vk" },
  { name: "fa-volume-down", icon: "Volume down" },
  { name: "fa-volume-off", icon: "Volume off" },
  { name: "fa-volume-up", icon: "Volume up" },
  { name: "fa-weibo", icon: "Weibo" },
  { name: "fa-weixin", icon: "Weixin" },
  { name: "fa-whatsapp", icon: "Whatsapp" },
  { name: "fa-wheelchair", icon: "Wheelchair" },
  { name: "fa-wifi", icon: "Wifi" },
  { name: "fa-wikipedia-w", icon: "Wikipedia w" },
  { name: "fa-windows", icon: "Windows" },
  { name: "fa-wordpress", icon: "Wordpress" },
  { name: "fa-wrench", icon: "Wrench" },
  { name: "fa-xing", icon: "Xing" },
  { name: "fa-xing-square", icon: "Xing square" },
  { name: "fa-y-combinator", icon: "Y combinator" },
  { name: "fa-yahoo", icon: "Yahoo" },
  { name: "fa-yelp", icon: "Yelp" },
  { name: "fa-youtube", icon: "Youtube" },
  { name: "fa-youtube-play", icon: "Youtube play" },
  { name: "fa-youtube-square", icon: "Youtube square" },
];

export default data;
